### ISSUE TITLE
cant get the module to import

### ISSUE THREAD

**Issue by tunip3** [tuxuser/py-durango-tools#1]
i cant get the module command to work could you give an example and what would be the recomended distro

**Comment by tuxuser** [comment]
Are you using python3? Can you post the exact command / output?

**Comment by tunip3** [comment]
i used this command

C:\Users\user\AppData\Local\Programs\Python\Python36-32\python.exe -m savegame_enum.py

and got this

Programs\Python\Python36-32\python.exe -m savegame_enum.py
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\user\OneDrive\Documents\xbox one reverse engineering\py-durango-tools-master\hdd\savegame_enum.py", line 11, in <module>
    from fileformat.savegame_container import ContainerIndex, ContainerBlob, CONTAINERS_INDEX
ModuleNotFoundError: No module named 'fileformat'

**Comment by tuxuser** [comment]
While being in the ROOT DIRECTORY of this repository, execute:

python.exe -m hdd.savegame_enum

Note: You need to be in the root dir so the dependencies can be resolved
Instead of giving a path with slashes you habe to seperate with "."
You dont append ".py" but pass only the module Name

You might have to add Python to your PATH variable.
See the README for the other possible paths

PS: Added some notes to the README
